{% set name = "sagemaker-headless-execution-driver" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sagemaker-headless-execution-driver-{{ version }}.tar.gz
  sha256: 18dc7a63a85f480eea7c2e8b5ffc9c7420fa19a4fdd6e616021ab7839f0f11af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - papermill >=2.4
    - nbconvert

test:
  imports:
    - sagemaker_headless_execution_driver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker
  summary: Execution Driver for Notebook Scheduler
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oztoprakmustafa
    - nargokul
    - pintaoz-aws
    - benieric
    - mufaddal-rohawala
    - C24IO
    - Aditi2424
    - akrishna1995
